#!/usr/bin/env bash
# hkreport — 互動安裝向導
# 在 repo 根目錄執行: bash install.sh

set -euo pipefail

# ---------- 樣式 ----------
BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'
RED=$'\033[31m'; CYAN=$'\033[36m'; RESET=$'\033[0m'

step()  { echo; echo "${BOLD}${CYAN}▶ $*${RESET}"; }
ok()    { echo "  ${GREEN}✓${RESET} $*"; }
warn()  { echo "  ${YELLOW}!${RESET} $*"; }
fail()  { echo "  ${RED}✗${RESET} $*" >&2; exit 1; }
ask()   { local var="$1" prompt="$2" default="${3:-}"; local input existing
         # Non-interactive mode: skip prompts; use existing env value, fall back to default.
         if [ "${HKREPORT_INSTALL_NONINTERACTIVE:-0}" = "1" ]; then
           existing="${!var:-}"
           if [ -n "$existing" ]; then
             return
           elif [ -n "$default" ]; then
             printf -v "$var" '%s' "$default"
             return
           else
             fail "non-interactive 模式下 $var 未設定且無默認值"
           fi
         fi
         if [ -n "$default" ]; then
           read -rp "    $prompt [${DIM}${default}${RESET}]: " input
           printf -v "$var" '%s' "${input:-$default}"
         else
           read -rp "    $prompt: " input
           printf -v "$var" '%s' "$input"
         fi
       }

# ---------- 0. 預檢 ----------
REPO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$REPO_ROOT"

if [ ! -f "scripts/run.sh" ] || [ ! -f "templates/launchd.plist.template" ]; then
  fail "請在 hkreport repo 根目錄執行此腳本"
fi

# ---------- 公司內建默認 ----------
# Futu 同事直接按 Enter 接受即可；外部用戶清空後填自己的官方端點。
DEFAULT_ANTHROPIC_BASE_URL="https://llm-proxy.futuoa.com/aws"

step "1/8  檢查環境依賴"
for cmd in python3 npx curl sed date launchctl; do
  if command -v "$cmd" >/dev/null 2>&1; then
    ok "$cmd 已安裝"
  else
    fail "缺少 $cmd — 請先安裝（npx 需要 Node.js: brew install node）"
  fi
done

PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
ok "python3 版本 $PY_VER"

# ---------- 2. 收集 API 密鑰 ----------
step "2/8  收集 API 密鑰"
echo "${DIM}  下列密鑰只會寫入 ~/.config/hkreport/env (chmod 600)，不會 commit 到 repo。${RESET}"
echo

ask ANTHROPIC_API_KEY    "Anthropic API Key (公司 AI 平台 user-key-... 或 anthropic.com sk-ant-...)"
[ -z "$ANTHROPIC_API_KEY" ] && fail "ANTHROPIC_API_KEY 必填"

ask ANTHROPIC_BASE_URL   "Anthropic Base URL (走公司代理；如要改走官方端點留空)" "$DEFAULT_ANTHROPIC_BASE_URL"

ask TAVILY_API_KEY       "Tavily API Key (https://app.tavily.com/)"
[ -z "$TAVILY_API_KEY" ] && fail "TAVILY_API_KEY 必填"

ask FIRECRAWL_API_KEY    "Firecrawl API Key (https://firecrawl.dev/)"
[ -z "$FIRECRAWL_API_KEY" ] && fail "FIRECRAWL_API_KEY 必填"

# ---------- 3. Surge 域名與認證 ----------
step "3/8  Surge 部署設定"
ask SURGE_DOMAIN         "Surge 域名 (例如 myreport.surge.sh)"
[ -z "$SURGE_DOMAIN" ] && fail "SURGE_DOMAIN 必填"
[[ "$SURGE_DOMAIN" != *.surge.sh && "$SURGE_DOMAIN" != *.* ]] && \
  warn "看起來不像合法域名，繼續中..."

ask SURGE_LOGIN          "Surge 註冊郵箱"
[ -z "$SURGE_LOGIN" ] && fail "SURGE_LOGIN 必填"

echo "    ${DIM}如需取得 Surge Token，在另一個終端執行: npx surge token${RESET}"
ask SURGE_TOKEN          "Surge Token"
[ -z "$SURGE_TOKEN" ] && fail "SURGE_TOKEN 必填"

# ---------- 4. 排期 ----------
step "4/8  發佈排期"
echo "${DIM}  launchd 會在每週指定 weekday 的指定時間觸發；wrapper 會做雙週篩選。${RESET}"
echo "${DIM}  Weekday: 1=週一, 2=週二, ..., 5=週五, 6=週六, 0=週日${RESET}"
echo

ask WEEKDAY              "觸發 weekday" "5"
ask HOUR                 "觸發小時 (0-23)" "9"
ask MINUTE               "觸發分鐘 (0-59)" "0"

# 計算下一個符合 weekday 的日期作為 ANCHOR_DATE 預設
DEFAULT_ANCHOR=$(python3 -c "
from datetime import date, timedelta
target_wd = $WEEKDAY  # 1=Mon..7=Sun in ISO; we accept 0=Sun launchd-style
iso_target = 7 if target_wd == 0 else target_wd
today = date.today()
delta = (iso_target - today.isoweekday()) % 7
delta = 7 if delta == 0 else delta  # 至少下週同一天
print((today + timedelta(days=delta)).isoformat())
")

echo
echo "${DIM}  錨點日期：第一期將在此日期 ${HOUR}:${MINUTE} 觸發；之後每 14 天一次。${RESET}"
echo "${DIM}  必須與 weekday=${WEEKDAY} 對應的日期一致。${RESET}"
ask ANCHOR_DATE          "錨點日期 (YYYY-MM-DD)" "$DEFAULT_ANCHOR"

# 驗證 ANCHOR_DATE 合法且 weekday 匹配
ACTUAL_WD=$(python3 -c "
from datetime import date
d = date.fromisoformat('$ANCHOR_DATE')
print(0 if d.isoweekday() == 7 else d.isoweekday())
" 2>/dev/null) || fail "ANCHOR_DATE 格式錯誤"

if [ "$ACTUAL_WD" != "$WEEKDAY" ]; then
  fail "錨點 $ANCHOR_DATE 的 weekday=$ACTUAL_WD 與設定 weekday=$WEEKDAY 不符"
fi
ok "錨點驗證通過 ($ANCHOR_DATE)"

ask MIN_GAP_DAYS         "最小間隔天數（防短期重跑）" "10"

# ---------- 5. 寫 env 檔 ----------
step "5/8  寫入 ~/.config/hkreport/env"
mkdir -p "$HOME/.config/hkreport"
ENV_FILE="$HOME/.config/hkreport/env"

if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  warn "已備份既有 env 到 ${ENV_FILE}.bak.*"
fi

cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')
export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
export ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL"
export TAVILY_API_KEY="$TAVILY_API_KEY"
export FIRECRAWL_API_KEY="$FIRECRAWL_API_KEY"
export SURGE_LOGIN="$SURGE_LOGIN"
export SURGE_TOKEN="$SURGE_TOKEN"
export SURGE_DOMAIN="$SURGE_DOMAIN"
export ANCHOR_DATE="$ANCHOR_DATE"
export MIN_GAP_DAYS="$MIN_GAP_DAYS"
EOF
chmod 600 "$ENV_FILE"
ok "已寫入 $ENV_FILE (chmod 600)"

# ---------- 6. Python venv ----------
step "6/8  建立 Python venv 並安裝依賴"
if [ ! -d ".venv" ]; then
  python3 -m venv .venv
  ok "已建立 .venv/"
else
  ok ".venv/ 已存在"
fi
./.venv/bin/pip install --quiet --upgrade pip
./.venv/bin/pip install --quiet -r requirements.txt
ok "依賴安裝完成"

# ---------- 7. 清零報告 + 寫 baseline ----------
step "7/8  初始化報告目錄"
ARCHIVE_DIR="reports/.archive_$(date +%Y%m%d%H%M%S)"
mkdir -p "$ARCHIVE_DIR"
moved=0
for f in reports/[0-9][0-9][0-9].html; do
  [ -e "$f" ] || continue
  mv "$f" "$ARCHIVE_DIR/"
  moved=$((moved+1))
done
[ -e reports/index.html ] && mv reports/index.html "$ARCHIVE_DIR/" || true
[ -e reports/baseline.json ] && mv reports/baseline.json "$ARCHIVE_DIR/" || true

if (( moved > 0 )); then
  ok "已將 $moved 份既有報告封存至 $ARCHIVE_DIR/"
else
  rmdir "$ARCHIVE_DIR" 2>/dev/null || true
  ok "報告目錄本就是乾淨的"
fi

# 計算 issue #001 應覆蓋的窗口：以 anchor 為終點往前 14 天
PREV_START=$(python3 -c "
from datetime import date, timedelta
a = date.fromisoformat('$ANCHOR_DATE')
print((a - timedelta(days=28)).strftime('%Y.%m.%d'))
")
PREV_END=$(python3 -c "
from datetime import date, timedelta
a = date.fromisoformat('$ANCHOR_DATE')
print((a - timedelta(days=14)).strftime('%Y.%m.%d'))
")

cat > reports/baseline.json <<EOF
{
  "issue": 0,
  "period": "${PREV_START}-${PREV_END:5}",
  "prev_period": "",
  "mode": "fresh",
  "fy_metrics": {},
  "rates": {},
  "unresolved_signals": [],
  "baseline_issues": [],
  "new_this_issue": [],
  "appstore_snapshot": {}
}
EOF
ok "已寫入 fresh baseline.json (#001 將覆蓋 ${PREV_END}+1 至 ${ANCHOR_DATE})"

# ---------- 8. 安裝 launchd ----------
step "8/8  註冊 launchd 任務"
USER_NAME="$(whoami)"
PLIST_LABEL="com.${USER_NAME}.hkreport"
PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"

mkdir -p "$HOME/Library/LaunchAgents"
sed \
  -e "s|{{PLIST_LABEL}}|${PLIST_LABEL}|g" \
  -e "s|{{REPO_ROOT}}|${REPO_ROOT}|g" \
  -e "s|{{HOME}}|${HOME}|g" \
  -e "s|{{WEEKDAY}}|${WEEKDAY}|g" \
  -e "s|{{HOUR}}|${HOUR}|g" \
  -e "s|{{MINUTE}}|${MINUTE}|g" \
  templates/launchd.plist.template > "$PLIST_PATH"

plutil -lint "$PLIST_PATH" >/dev/null || fail "生成的 plist 格式錯誤"
ok "已生成 $PLIST_PATH"

# 先 bootout 舊版（若存在），再 bootstrap
launchctl bootout "gui/$(id -u)" "$PLIST_PATH" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH"
ok "launchd 任務已註冊：$PLIST_LABEL"

if launchctl list | grep -q "$PLIST_LABEL"; then
  ok "驗證通過：launchctl list 可見"
else
  warn "未在 launchctl list 中找到，請手動檢查"
fi

# ---------- 完成 ----------
cat <<EOF

${BOLD}${GREEN}✓ 安裝完成${RESET}

  ${BOLD}排期：${RESET}每雙週 weekday=${WEEKDAY} ${HOUR}:${MINUTE}（錨點 ${ANCHOR_DATE}）
  ${BOLD}域名：${RESET}https://${SURGE_DOMAIN}
  ${BOLD}日誌：${RESET}~/Library/Logs/hkreport.log
  ${BOLD}配置：${RESET}${ENV_FILE}
  ${BOLD}plist：${RESET}${PLIST_PATH}

${BOLD}下一步：${RESET}
  1. 立即試跑（會 SKIP，驗證 wrapper 邏輯正確）：
     ${DIM}launchctl kickstart -k gui/\$(id -u) ${PLIST_LABEL}${RESET}
     ${DIM}tail -n 30 ~/Library/Logs/hkreport.log${RESET}

  2. 強制跑一次完整 pipeline 以驗證密鑰/部署（會真正發佈 #001）：
     ${DIM}source ${ENV_FILE} && .venv/bin/python scripts/generate.py && .venv/bin/python scripts/deploy.py${RESET}
     ${DIM}curl -s https://${SURGE_DOMAIN}/ | head -5${RESET}

  3. 確認首期自動觸發時間：${BOLD}${ANCHOR_DATE} ${HOUR}:${MINUTE}${RESET}

${BOLD}運維：${RESET}
  暫停：${DIM}launchctl bootout gui/\$(id -u) ${PLIST_PATH}${RESET}
  恢復：${DIM}launchctl bootstrap gui/\$(id -u) ${PLIST_PATH}${RESET}
  卸載：${DIM}bash uninstall.sh${RESET}

EOF
